name = "voting-power-bot"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
# Environment variables will be set via wrangler secret
# TELEGRAM_BOT_TOKEN will be bound automatically when set as secret 